project:
  type: website
  output-dir: _site

website:
  title: "Michael Vargo"
  site-url: "https://mbvargo.github.io/" 
  description: "Urban Planning + Data Analytics"
  favicon: images/favicon.svg
  navbar:
    background: "#3A59A0"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Web Projects
      - href: portfolio/index.qmd
        text: Portfolio
      # - href: blog/index.qmd # !!! TBD !!!
      #   text: Blog
      - href: resume.qmd
        text: Resume
    right:
      - icon: linkedin
        href: https://linkedin.com/in/mbvargo
      - icon: github
        href: https://github.com/mbvargo
  page-footer:
    background: "#3A59A0"
    foreground: "#FFFFFF"
    left: "© 2026 Michael Vargo"

format:
  html:
    theme: [minty, custom.scss]
    cap-location: top 
      # light: [minty, custom-light.scss] # Eventually I'll do this
      # dark: [minty, custom-dark.scss]   # And this too
    css: styles.css
    toc: false
    grid:
      body-width: 900px
    
